CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    employee_id VARCHAR(128) UNIQUE NOT NULL,
    full_name TEXT NOT NULL,
    role BIGINT NOT NULL REFERENCES roles(id) ON DELETE RESTRICT
);